'use client'

import { useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import type { NewsSource } from '@/lib/schemas'

const TYPE_COLORS: Record<string, string> = {
  official: '#4fc3ff',
  wire: '#ffb020',
  specialty: '#a78bfa',
}

interface SourcesPanelProps {
  sources: NewsSource[]
  isOpen: boolean
  onClose: () => void
}

export default function SourcesPanel({ sources, isOpen, onClose }: SourcesPanelProps) {
  useEffect(() => {
    function handleKey(e: KeyboardEvent) {
      if (e.key === 'Escape') onClose()
    }
    window.addEventListener('keydown', handleKey)
    return () => window.removeEventListener('keydown', handleKey)
  }, [onClose])

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          <motion.div
            key="sources-backdrop"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50"
            style={{ background: 'rgba(10,13,18,0.7)' }}
            onClick={onClose}
          />
          <motion.div
            key="sources-panel"
            initial={{ x: '100%' }}
            animate={{ x: 0 }}
            exit={{ x: '100%' }}
            transition={{ type: 'tween', duration: 0.2 }}
            className="fixed top-0 right-0 bottom-0 z-50 w-72 border-l border-[#2d3748] flex flex-col overflow-hidden"
            style={{ background: '#0f1318' }}
          >
            <div className="flex items-center justify-between px-4 py-3 border-b border-[#1f2937]">
              <span className="text-[9px] font-mono-ui text-[#d4d4d4]/50 tracking-widest uppercase">
                Monitored Sources
              </span>
              <button
                onClick={onClose}
                className="text-[#d4d4d4]/30 hover:text-[#d4d4d4] transition-colors text-xl leading-none"
                aria-label="Close"
              >
                ×
              </button>
            </div>

            <div className="flex-1 overflow-y-auto divide-y divide-[#1f2937]">
              {sources.map((source) => (
                <div key={source.name} className="flex items-center justify-between px-4 py-3">
                  <div>
                    <div className="text-[11px] font-mono-ui text-[#ffffff] font-bold">{source.name}</div>
                    <a
                      href={source.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-[9px] font-body text-[#4fc3ff]/60 hover:text-[#4fc3ff] transition-colors break-all"
                    >
                      {source.url.replace(/^https?:\/\//, '')}
                    </a>
                  </div>
                  <span
                    className="ml-3 shrink-0 px-1.5 py-px text-[8px] font-mono-ui font-bold tracking-widest uppercase border"
                    style={{
                      color: TYPE_COLORS[source.type] ?? '#d4d4d4',
                      borderColor: `${TYPE_COLORS[source.type] ?? '#d4d4d4'}50`,
                      borderRadius: 1,
                    }}
                  >
                    {source.type}
                  </span>
                </div>
              ))}
            </div>

            <div className="px-4 py-2 border-t border-[#1f2937]">
              <p className="text-[9px] font-body text-[#d4d4d4]/30 leading-relaxed">
                News feed refreshed hourly via Vercel Cron. Summaries generated by Claude AI.
              </p>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  )
}
